app.rb
close #8 
Could you please review?
and please merge after the PR(#5) is merged.
This PR includes the commits related with #5.
Should I rebase?
=> Return json

.gitignore, app.rb, public/assets/css/Footer-Clean.css, public/assets/css/Header-Blue.css, public/assets/css/styles.css, views/index.erb
@chaspy Hi, I implemented the top page design as a draft version.  Could you check this design and give me some advice?
close #11 
close #12
=> Add top page design

Procfile
ref: https://github.com/chaspy/favsearch/issues/17
=> Change Port

Gemfile, Gemfile.lock, newrelic.yml
heroku add-on
https://rpm.newrelic.com/accounts/2134862/applications/setup#ruby
=> Try NewRelic

.circleci/config.yml
close: https://github.com/chaspy/favsearch/issues/19
=> CI Setting

public/favorite.html
ref: https://github.com/axios/axios
=> With credential when request by axios

app.rb, views/favorite.erb
Request to REST API corresponded to each host name.
=> Get domain name

views/favorite.erb
https://favsearch-pr-33.herokuapp.com
=> Remove link to logout

public/assets/css/Footer-Clean.css, views/index.erb
ref: http://www.sharelinkgenerator.com
=> Update social sharing

app.json, app.rb, views/favorite.erb
close: https://github.com/chaspy/favsearch/issues/43
=> Make it searchable by screen name

app.rb, public/assets/css/styles.css, views/favorite.erb
close: https://github.com/chaspy/favsearch/issues/44
=> Display Tweet's time

views/favorite.erb
ref: https://github.com/chaspy/favsearch/issues/40
ref(toLowerCase): https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/String/toLowerCase
=> Uppercase and lowercase are not distinguished to search tweet's text

app.rb
ref: https://github.com/chaspy/favsearch/issues/6
=> Get more 200 favorites

views/favorite.erb, views/index.erb
close: https://github.com/chaspy/favsearch/issues/53
=> Add tracking code

public/assets/js/stringfilter.js, views/favorite.erb
close #40 
-  Resolve `toLowerCase()` error
-  Searchable distinguished without between hiragana and katakana
@chaspy Please review! If there is no problem, could you please merge into master.
=> Hiragana katakana

newrelic.yml
ref: https://github.com/chaspy/favsearch/issues/46
=> Fix app name

app.rb
=> Add requirement for newrelic

app.rb
=> Get 1000 favorites

public/assets/css/styles.css, views/favorite.erb
@chaspy It is completed to implement the notification during the request. Please review and merge.
=> Notify loding status

app.rb
ref: #79 
Can't load favorites
=> Fix internal http request

app.rb
Better to return with application/json instead of text/html
=> Return application/json content type
